### ISSUE TITLE
poc: todo list

### ISSUE THREAD

**Issue by AlexandreHiroyuki** [AlexandreHiroyuki/mock-devboard#3]
# Features

- Home / Session Begin Page
  - Sign Up
  - Sign In
- Dashboard
  - Device List
    - Add a new device
    - Edit existing device
    - Read device data
    - Delete device
  - Device Group Report

## TODO

- [x] Setup Environment.
  - [x] Set up front-end environment.
  - [x] Set up back-end environment.
- [x] Connect Postgres database.
- [x] JWT authentication.
  - [x] Sign In page.
  - [x] Sign Up page.
  - [x] Form validation.
  - [x] User endpoint.
  - [x] Request validation.
- [x] Dashboard page.
- [x] Device list component.
- [x] Specific device endpoint.
  - [x] Add a new device operation.
  - [x] Add a new device UI component.
  - [x] Edit existing device operation.
  - [x] Edit existing device UI component.
  - [x] Read device data operation.
  - [x] Read device data UI component.
  - [x] Delete device operation.
  - [x] Delete device UI component.

### Extras

- [ ] Device Group Report page.
- [ ] Use Scalar for docs.
- [ ] Create a simple logo.

**Comment by AlexandreHiroyuki** [comment]
- [x] Integrate Zod and Hook Forms to the auth form.
- [x] Connect to the back-end.
